# Generated by Django 4.2.6 on 2023-10-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_description_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=300, null=None, verbose_name='Описание'),
        ),
    ]
