# Generated by Django 4.2.6 on 2023-10-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
    ]
